//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace MICROS.Modules.MyCentralSiteConfiguration {
    
    
    public partial class ModuleStyleEditor {
        
        /// <summary>
        /// tbHiddenCurrentEditNode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden tbHiddenCurrentEditNode;
        
        /// <summary>
        /// HiddenImageControlArray control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden HiddenImageControlArray;
        
        /// <summary>
        /// ButtonApply control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button ButtonApply;
        
        /// <summary>
        /// MyCentralModuleStyleSetting_FileLoader1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputFile MyCentralModuleStyleSetting_FileLoader1;
        
        /// <summary>
        /// MyCentralModuleStyleSetting_FileLoader2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputFile MyCentralModuleStyleSetting_FileLoader2;
        
        /// <summary>
        /// MyCentralModuleStyleSetting_FileLoader3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputFile MyCentralModuleStyleSetting_FileLoader3;
        
        /// <summary>
        /// MyCentralModuleStyleSetting_FileLoader4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputFile MyCentralModuleStyleSetting_FileLoader4;
        
        /// <summary>
        /// MyCentralModuleStyleSetting_FileLoader5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputFile MyCentralModuleStyleSetting_FileLoader5;
        
        /// <summary>
        /// MyCentralModuleStyleSetting_FileLoader6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputFile MyCentralModuleStyleSetting_FileLoader6;
        
        /// <summary>
        /// MyCentralModuleStyleSetting_FileLoader7 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputFile MyCentralModuleStyleSetting_FileLoader7;
        
        /// <summary>
        /// MyCentralModuleStyleSetting_FileLoader8 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputFile MyCentralModuleStyleSetting_FileLoader8;
        
        /// <summary>
        /// MyCentralModuleStyleSetting_FileLoader9 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputFile MyCentralModuleStyleSetting_FileLoader9;
        
        /// <summary>
        /// MyCentralModuleStyleSetting_FileLoader10 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputFile MyCentralModuleStyleSetting_FileLoader10;
        
        /// <summary>
        /// MyCentralModuleStyleSetting_FileLoader11 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputFile MyCentralModuleStyleSetting_FileLoader11;
        
        /// <summary>
        /// MyCentralModuleStyleSetting_FileLoader12 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputFile MyCentralModuleStyleSetting_FileLoader12;
        
        /// <summary>
        /// MyCentralModuleStyleSetting_FileLoader13 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputFile MyCentralModuleStyleSetting_FileLoader13;
        
        /// <summary>
        /// MyCentralModuleStyleSetting_FileLoader14 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputFile MyCentralModuleStyleSetting_FileLoader14;
        
        /// <summary>
        /// MyCentralModuleStyleSetting_FileLoader15 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputFile MyCentralModuleStyleSetting_FileLoader15;
        
        /// <summary>
        /// MyCentralModuleStyleSetting_FileLoader16 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputFile MyCentralModuleStyleSetting_FileLoader16;
        
        /// <summary>
        /// MyCentralModuleStyleSetting_FileLoader17 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputFile MyCentralModuleStyleSetting_FileLoader17;
        
        /// <summary>
        /// MyCentralModuleStyleSetting_FileLoader18 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputFile MyCentralModuleStyleSetting_FileLoader18;
        
        /// <summary>
        /// MyCentralModuleStyleSetting_FileLoader19 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputFile MyCentralModuleStyleSetting_FileLoader19;
        
        /// <summary>
        /// MyCentralModuleStyleSetting_FileLoader20 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputFile MyCentralModuleStyleSetting_FileLoader20;
    }
}
